version: '3.8'

services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "mysql://root:example@mysql:3306/testdb"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: